FROM nginx:alpine

WORKDIR /app
# Copy built app to nginx
COPY ./dist/apple_health_social/browser /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
